### ISSUE TITLE
[ROS2] Install ROS2_java on an EV3 Brick

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#256]
```gherkin
Feature: Test ROS2 with Java on an EV3 Brick
It is necessary to analyze the difficult to use the Java library for ROS2

    Scenario: Test in local the library
        Given The library ros2_java
        Then It is necessary to test the classic example Listener & Talker
        And evaluate how to complex is the usage of the library for a Robotics environment.
```

**ROS2_java:**
https://github.com/esteve/ros2_java

Related issue:
https://github.com/esteve/ros2_java/issues/30

**Comment by jabrena** [comment]
It is necessary to install this tool:
https://github.com/dirk-thomas/vcstool
https://packages.debian.org/sid/python-vcstools

**Comment by jabrena** [comment]
vi /etc/apt/sources.list

deb http://http.debian.net/debian sid main

**Comment by jabrena** [comment]
```
robot@ev3dev:/etc/apt$ sudo apt-get install python-vcstool
Reading package lists... Done
Building dependency tree        
Reading state information... Done
E: Unable to locate package python-vcstool
robot@ev3dev:/etc/apt$ 

```

**Comment by esteve** [comment]
@jabrena `vcstool` can be installed directly from PyPI:

`$ sudo pip3 install vcstool`

However, since the Raspberry Pi is fairly slow, you can use `CMake` toolchain (for example https://github.com/ruslo/polly) and crosscompile `ros2_java` instead of compiling on the RPI itself. I can give you more details tomorrow about the whole process, but basically you pass `--cmake-args -DCMAKE_TOOLCHAIN_FILE=PATH_TO_THE_POLLY_TOOLCHAIN --` to ament and follow https://github.com/ruslo/polly/wiki/Toolchain-list#raspberrypi2-cxx11 (similar to the ROS2 bindings for the iPhone https://github.com/esteve/ros2_objc#ios)

I've used this to crosscompile ROS2 to the RaspberryPi and the ODroid and it works pretty well.

**Comment by jabrena** [comment]
Yes, of course, I will do it.

If you like, I will test in this order:

```
OSX > Raspi 3 > EV3 Brick.
```

**Comment by jabrena** [comment]
It is not a priority
