### ISSUE TITLE
Expose some EV3 Sensor Constants to be used by ROS publishers

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#396]
YThis issue requires some analysis because expose some Sensor data in a public way to be used by Third party libraries.

Some Sensors like EV3IRSensor or EV3UltrasonicSensor are used by the ROS library:
https://github.com/ev3dev-lang-java/ros to send messages with the type: "sensor_msgs/Range"
http://docs.ros.org/api/sensor_msgs/html/msg/Range.html

This ROS Message, has the following constructor and it used to publish the information to ROS:

``` java
final Message message = new Range(
                    header,
                    Range.INFRARED,
                    0.5f,
                    0.05f,
                    0.55f,
                    distance
            );
```

``` java
            final Message message = new Range(
                    header,
                    Range.ULTRASOUND,
                    0.5f,
                    0.05f,
                    2.55f,
                    distance
            );
```

The values about min_range and max_range are used in the EV3 Sensor class so if the class expose the values it is possible to be reused.

to publish information to 

**EV3IRSensor.java:**

``` java
        @Override
        public void fetchSample(float[] sample, int offset) {
            switchMode(MODE, SWITCH_DELAY);
    		float raw = Sysfs.readFloat(this.pathDevice + "/" +  VALUE0);

            if (raw < 5) sample[offset]=0;
            else if (raw > 55) sample[offset]=Float.POSITIVE_INFINITY;
            else sample[offset]= raw * toSI;
        }
``` 

**EV3UltrasonicSensor.java:**

```
       @Override
        public void fetchSample(float[] sample, int offset) {
            switchMode(MODE, SWITCH_DELAY);
            float raw = Sysfs.readFloat(this.pathDevice + "/" +  VALUE0);

            if (raw<5) sample[offset]=0;
            else if (raw > 2550) sample[offset]=Float.POSITIVE_INFINITY;
            else sample[offset]= (raw * toSI)/10;
        }
```

The idea is to define constants for min/max variables like a Sensor definition and expose as a final static public in order to be used by everyone because is part of the definition and usage of the sensor.

Hi @Asw1n, @gloomyandy   at is your opinion?

**Comment by jabrena** [comment]
I am going to create a `feature` branch in order to add the solution.

**Comment by aswin** [comment]
Hi, this is @aswin but I believe you have tagged the wrong person? :)

**Comment by jabrena** [comment]
Hi @aswin, sorry mate. this is the @Asw1n for this matter.

Good weekend. :)

**Comment by jabrena** [comment]
Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/347

**Comment by jabrena** [comment]
No answer. Included.

**Comment by Asw1n** [comment]
Hi Juan,

Sorry it took me so long to reply. I've been on holidays and also very much
occupied with other matters.

I think I would create a SampleproviderMetadata class. This class has a
LinkedList member that holds the actual metadata in named items. The class
has methods to maintain the list and to output it formatted for ROS. The
class is instantiated and filled during creation of a SampleProvider class.
So that there is always exactly one instance of the metadata class for each
type of SampleProvider. The SampleProvider interface should have a method
to retrieve the SampleproviderMetadata object.

Does this makes sense to you?

Beware that not all Sensors provide data that is easily described in
metadata.

Also take note that filters are also SampleProviders. They alter some of
the metadata and maybe even add metadata. Once you start doing metadata
you'll have to go all the way. It will require a lot of thinking. The
coding will be the easy part.

Best,
Aswin

Op 15 sep. 2017 19:56 schreef "Juan Antonio Breña Moral" <
notifications@github.com>:
